INSERT INTO Categories (id_category, category) VALUES
(0, 'Medical' ),
(1, 'City Building' ),
(2, 'Medieval' ),
(3, 'Territory Building' ),
(4, 'Economic' ),
(5, 'Negotiation' ),
(6, 'Ancient' ),
(7, 'Card Game' ),
(8, 'Civilization' ),
(9, 'Trains' ),
(10, 'Deduction' ),
(11, 'Party Game' ),
(12, 'Spies/Secret Agents' ),
(13, 'Word Game' ),
(14, 'Environmental' ),
(15, 'Industry / Manufacturing' ),
(16, 'Science Fiction' ),
(17, 'Space Exploration' ),
(18, 'Animals' ),
(19, 'Farming' );
