INSERT INTO Categories (id_category, category) VALUES
(0, 'Medical'),
(1, 'City Building'),
(2, 'Medieval'),
(3, 'Territory Building'),
(4, 'Economic'),
(5, 'Negotiation'),
(6, 'Ancient'),
(7, 'Card Game'),
(8, 'Civilization'),
(9, 'Trains'),
(10, 'Deduction'),
(11, 'Party Game'),
(12, 'Spies/Secret Agents'),
(13, 'Word Game'),
(14, 'Environmental'),
(15, 'Industry / Manufacturing'),
(16, 'Science Fiction'),
(17, 'Space Exploration'),
(18, 'Animals'),
(19, 'Farming'),
(20, 'Renaissance'),
(21, 'Fighting'),
(22, 'Miniatures'),
(23, 'Fantasy'),
(24, 'Abstract Strategy'),
(25, 'Puzzle'),
(26, 'Dice'),
(27, 'Movies / TV / Radio theme'),
(28, 'Educational'),
(29, 'Humor'),
(30, 'Bluffing'),
(31, 'Adventure'),
(32, 'Exploration'),
(33, 'Prehistoric'),
(34, 'Modern Warfare'),
(35, 'Political'),
(36, 'Wargame'),
(37, 'Memory'),
(38, 'Horror'),
(39, 'Zombies'),
(40, 'Mythology'),
(41, 'Novel-based'),
(42, 'Murder/Mystery'),
(43, 'Arabian'),
(44, 'Collectible Components'),
(45, 'American West'),
(46, 'Age of Reason'),
(47, 'Nautical'),
(48, 'Travel'),
(49, 'Real-time'),
(50, 'Transportation'),
(51, 'World War II'),
(52, 'Civil War'),
(53, 'Post-Napoleonic'),
(54, 'Mature / Adult'),
(55, 'Comic Book / Strip'),
(56, 'Pirates'),
(57, 'Print & Play'),
(58, 'Religious'),
(59, 'Racing'),
(60, 'Aviation / Flight'),
(61, 'Number'),
(62, 'Maze'),
(63, 'Sports'),
(64, 'Action / Dexterity'),
(65, 'Electronic'),
(66, 'Video Game Theme'),
(67, 'Napoleonic'),
(68, 'Children''s Game'),
(69, 'Trivia'),
(70, 'Mafia'),
(71, 'Pike and Shot'),
(72, 'World War I'),
(73, 'Music'),
(74, 'Math'),
(75, 'American Indian Wars'),
(76, 'Game System'),
(77, 'American Civil War'),
(78, 'American Revolutionary War'),
(79, 'Expansion for Base-game'),
(80, 'Vietnam War'),
(81, 'Book'),
(82, 'Korean War');
